package foreverse.afmsynthesis.generator

import org.scalatest.Matchers
import org.scalatest.FlatSpec
import examples.RandomConfigurations
import java.io.File

class FAMAGenerator extends FlatSpec with Matchers {

	val GENERATED_AFM_DIR = "../AFMGenerator/generated_AFMs/"
  
     "Product generator" should "list the product of the models generated by BeTTy in CSV files" in {
	  val productGenerator = new RandomConfigurations
	  val modelsDir = new File(GENERATED_AFM_DIR)

	  for (inputFile <- modelsDir.listFiles()) {
		  val inputName = inputFile.getName()
		  val outputName = inputName.substring(0, inputName.length - 4) + ".csv"
		  val outputFile = new File(GENERATED_AFM_DIR + outputName)
		  println("Generating products for " + inputName)
		  productGenerator.generateProducts(inputFile, outputFile)
	  }
	  
  }
  
}